version: "3.9"

services:
  db:
    image: postgres:15
    container_name: drinkit_db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: dodo_stats
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: drinkit_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: drinkit_app
    depends_on:
      - db
      - redis
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../drinkit_stock_transfers:/app/drinkit_stock_transfers
      - ../storage:/app/storage
      - ../logs:/app/logs
      - ../drinkit_stock_transfers/tokens.json:/app/drinkit_stock_transfers/tokens.json
      - ../drinkit_stock_transfers/google_api_key.json:/app/drinkit_stock_transfers/google_api_key.json
volumes:
  db_data:
  redis_data:
